export default [

  [
    {
      "date": "2021-06-04",
      "startTime": "10:00",
      "endTime": "11:00",
      "activityName": "Activity 1",
      "availableSpots": 10,
      "bookedCount": 0,
      "maxGuests": 10
    },
    {
      "date": "2021-06-04",
      "startTime": "11:00",
      "endTime": "12:00",
      "activityName": "Activity 1",
      "availableSpots": 7,
      "bookedCount": 3,
      "maxGuests": 10
    },
    {
      "date": "2021-06-04",
      "startTime": "12:30",
      "endTime": "14:00",
      "activityName": "Activity 2",
      "availableSpots": 14,
      "bookedCount": 1,
      "maxGuests": 15
    }
  ],

  [
    {
      "date": "2021-06-05",
      "startTime": "10:00",
      "endTime": "11:00",
      "activityName": "Activity 1",
      "availableSpots": 9,
      "bookedCount": 1,
      "maxGuests": 10
    },
    {
      "date": "2021-06-05",
      "startTime": "10:00",
      "endTime": "12:00",
      "activityName": "Activity 2",
      "availableSpots": 0,
      "bookedCount": 15,
      "maxGuests": 15
    },
    {
      "date": "2021-06-05",
      "startTime": "11:30",
      "endTime": "13:00",
      "activityName": "Activity 2",
      "availableSpots": 10,
      "bookedCount": 5,
      "maxGuests": 15
    },
    {
      "date": "2021-06-05",
      "startTime": "12:30",
      "endTime": "14:00",
      "activityName": "Activity 1",
      "availableSpots": 0,
      "bookedCount": 10,
      "maxGuests": 10
    },
    {
      "date": "2021-06-05",
      "startTime": "15:00",
      "endTime": "16:30",
      "activityName": "Activity 1",
      "availableSpots": 8,
      "bookedCount": 2,
      "maxGuests": 10
    }
  ],
  [
    {
      "date": "2021-08-30",
      "startTime": "6:00",
      "endTime": "6:30",
      "activityName": "Gio Wakes Everyone Up",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1],
    },
    {
      "date": "2021-08-30",
      "startTime": "6:30",
      "endTime": "7:00",
      "activityName": "All Puppies Eat",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1, 2, 3],
    },
    {
      "date": "2021-08-30",
      "startTime": "7:00",
      "endTime": "15:00",
      "activityName": "Walter and Gabby Sleep",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [2, 3],
    },
    {
      "date": "2021-08-30",
      "startTime": "8:00",
      "endTime": "11:00",
      "activityName": "Gio Supervises Dan's Work",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1],
    },
    {
      "date": "2021-08-30",
      "startTime": "12:00",
      "endTime": "12:30",
      "activityName": "Gio Demands Lunch",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1],
    },
    {
      "date": "2021-08-30",
      "startTime": "15:00",
      "endTime": "17:00",
      "activityName": "All Puppies Bully Dan for Dinner",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1, 2, 3],
    },
    {
      "date": "2021-08-30",
      "startTime": "17:00",
      "endTime": "17:30",
      "activityName": "All Puppies Eat Dinner",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1, 2, 3],
    },
    {
      "date": "2021-08-30",
      "startTime": "17:00",
      "endTime": "17:30",
      "activityName": "Gio Tries to Eat Everyone's Dinner",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1, 2, 3],
    },
    {
      "date": "2021-08-30",
      "startTime": "17:00",
      "endTime": "19:00",
      "activityName": "All Puppies Bully Dan for Walks",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1, 2, 3],
    },
    {
      "date": "2021-08-30",
      "startTime": "20:00",
      "endTime": "22:00",
      "activityName": "Gio Supervises Dan's Work",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1],
    },
    {
      "date": "2021-08-30",
      "startTime": "20:00",
      "endTime": "23:59",
      "activityName": "Gabby and Walter Sleep",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [2, 3],
    },
    {
      "date": "2021-08-30",
      "startTime": "22:00",
      "endTime": "23:59",
      "activityName": "Gio Makes Dan Go to Sleep",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1],
    },
    {
      "date": "2021-08-30",
      "startTime": "22:00",
      "endTime": "23:59",
      "activityName": "Gio Sleeps",
      "availableSpots": 5,
      "bookedCount": 1,
      "maxGuests": 5,
      "owners": [1],
    },
  ]
];